### ISSUE TITLE
support online rendering

### ISSUE THREAD

**Issue by xiaotaw** [weigao95/surfelwarp#37]
Hi, I noticed surfelwarp support offline rendering. It's very cool to display rendered images (e.g. live_abedo.png) on screen, instead of saving into local files. 

Simply comment out `glfwWindowHint(GLFW_VISIBLE, GL_FALSE);`, it just displays a black window. HAHA

Thank you!

**Comment by weigao95** [comment]
You need to delete the `glBindFramebuffer` in the drawing function. Here is a tutorial: https://learnopengl.com/Advanced-OpenGL/Framebuffers

**Comment by xiaotaw** [comment]
Done, Thx!

**Comment by daxiong-123** [comment]
Hello, could you tell me which `glBindFramebuffer` should I delete? @xiaotaw

**Comment by xiaotaw** [comment]
> Hello, could you tell me which `glBindFramebuffer` should I delete? @xiaotaw

Always set the second parameter to be 0, and the pics/images will be updated in windows.
glBindFramebuffer(GL_FRAMEBUFFER, 0);  

Note: Based on the current code, you also have to set 'offline rendering' with True.

**Comment by daxiong-123** [comment]
> > Hello, could you tell me which `glBindFramebuffer` should I delete? @xiaotaw
> 
> Always set the second parameter to be 0, and the pics/images will be updated in windows.
> glBindFramebuffer(GL_FRAMEBUFFER, 0);
> 
> Note: Based on the current code, you also have to set 'offline rendering' with True.

Thanks, i tried but still failed. Maybe I should look through the whole project.

**Comment by xiaotaw** [comment]
@daxiong-123 try one more time? it should work:
1. comment out glfwWindowHint(GLFW_VISIBLE, GL_FALSE) to make sure the blank window appears
2. find function `drawVisualizationMap` in file RendererDraw.cpp, and 
modify glBindFramebuffer ( line 191)
3. in the same function `drawVisualizationMap`, insert `glfwSwapBuffers(mGLFWwindow);` before cleanup code (line 218).

**Comment by 411066282** [comment]
@xiaotaw dear,   could you share your whole modified code project to me? I just failed this, thank you very much!                      yaoyao-501@163.com

**Comment by xiaotaw** [comment]
> @xiaotaw dear, could you share your whole modified code project to me? I just failed this, thank you very much! [yaoyao-501@163.com](mailto:yaoyao-501@163.com)

Here is my modified code. Hope its commit log would help.  https://github.com/xiaotaw/surfelwarp

**Comment by 411066282** [comment]
@xiaotaw thank you very much! you are one  good and kind guy!!!
